version: '3.8'

services:
  couchbase:
    image: couchbase:latest
    ports:
      - "8091-8096:8091-8096"
      - "11210:11210"
    environment:
      COUCHBASE_ADMINISTRATOR_USERNAME: your-admin-username
      COUCHBASE_ADMINISTRATOR_PASSWORD: your-password
    volumes:
      - "couchbase_data:/opt/couchbase/var"

  todo-app:
    image: todo-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      ["8080:8080"]
    environment:
      COUCHBASE_HOST: couchbase://localhost
      COUCHBASE_USERNAME: your-username
      COUCHBASE_PASSWORD: your-password
      COUCHBASE_BUCKET_NAME: todo-app
    depends_on: [couchbase]

volumes:
  couchbase_data:
